modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://example.com" #optional
[[mods]] #mandatory
modId="advancedelectricity" #mandatory
version="${version}" #mandatory
displayName="Advanced Electricity" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://example.com" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="example.png" #optional
# A text field displayed in the mod UI
credits="Palomox" #optional
# A text field displayed in the mod UI
authors="Palomox" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Lets you manage electricity a way you haven't before
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.advancedelectricity]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.advancedelectricity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
